id: P15448D05
initial_creation_type: ocr
source_metadata:
  volumes:
    0c0b1c994d3d4b1da95c16cf7dab38d1:
      base_file: v096.txt
      image_group_id: I1PD95941
      title: འདོད་པའི་ཡོན་ཏན་ལྔའི་ཉེས་དམིགས་བཤད་པ།
      total_pages: 1144
      volume_number: 96
