id: D83141F44
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-01-11T09:47:27+00:00'
last_modified: '2022-05-30T04:23:07.707373+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    '5584':
      image_group_id: I1PD95941
      title: འདོད་པའི་ཡོན་ཏན་ལྔའི་ཉེས་དམིགས་བཤད་པ།
      total_pages: 1144
      order: 96
      base_file: 5584.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
